In [1]:
# Library Import
from mesa.batchrunner import BatchRunner
from road_network_model.model import RoadNetworkModel, number_idle_cars, number_move_cars, number_finished_cars, simulation_minutes, number_office, number_residence, mean_travel_time, std_travel_time

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Mesa BatchRunner
fixed_params = {"number_of_cars": 30,
                "width": 100,
                "height": 100,
                "is_odd_even_policy_enabled": True
               }

variable_params = {"policy_range_time": [
                        '7_10_and_16_19',
                        '8_11_and_17_20',
                        '6_9_and_15_18',
                        '8_9_and_17_18',
                        '6_11_and_15_20'
                    ],
                    "is_odd_date": [True, False]
                  }
batch_run = BatchRunner(RoadNetworkModel,
                        variable_parameters=variable_params,
                        fixed_parameters=fixed_params,
                        iterations=5,
                        max_steps=1500,
                        model_reporters={
                            "Idle": number_idle_cars,
                            "Move": number_move_cars,
                            "Finished": number_finished_cars,
                            "SimulationMinutes": simulation_minutes,
                            "ToOffice": number_office,
                            "ToResidence": number_residence,
                            "MeanTravelTime": mean_travel_time,
                            "StdTravelTime": std_travel_time
                        }
                       )

batch_run.run_all()

batch_run_results = batch_run.get_model_vars_dataframe()
batch_run_results.head()

10it [32:05, 192.60s/it]

,policy_range_time,is_odd_date,Run,Finished,Idle,MeanTravelTime,Move,SimulationMinutes,StdTravelTime,ToOffice,ToResidence,number_of_cars,width,height,is_odd_even_policy_enabled
0,7_10_and_16_19,True,0,27,0,486.266667,3,1440,387.889583,0,0,30,100,100,True
1,7_10_and_16_19,False,1,28,0,520.366667,2,1440,382.380830,0,0,30,100,100,True
2,8_11_and_17_20,True,2,28,0,477.666667,2,1440,393.978369,0,0,30,100,100,True
3,8_11_and_17_20,False,3,26,0,495.733333,4,1440,397.914809,0,0,30,100,100,True
4,6_9_and_15_18,True,4,27,0,486.733333,3,1440,413.178729,0,0,30,100,100,True

In [3]:
batch_run_results

,policy_range_time,is_odd_date,Run,Finished,Idle,MeanTravelTime,Move,SimulationMinutes,StdTravelTime,ToOffice,ToResidence,number_of_cars,width,height,is_odd_even_policy_enabled
0,7_10_and_16_19,True,0,27,0,486.266667,3,1440,387.889583,0,0,30,100,100,True
1,7_10_and_16_19,False,1,28,0,520.366667,2,1440,382.380830,0,0,30,100,100,True
2,8_11_and_17_20,True,2,28,0,477.666667,2,1440,393.978369,0,0,30,100,100,True
3,8_11_and_17_20,False,3,26,0,495.733333,4,1440,397.914809,0,0,30,100,100,True
4,6_9_and_15_18,True,4,27,0,486.733333,3,1440,413.178729,0,0,30,100,100,True
5,6_9_and_15_18,False,5,27,0,454.466667,3,1440,394.302653,0,0,30,100,100,True
6,8_9_and_17_18,True,6,27,0,461.266667,3,1440,381.279769,0,0,30,100,100,True
7,8_9_and_17_18,False,7,29,0,490.266667,1,1440,386.890073,0,0,30,100,100,True
8,6_11_and_15_20,True,8,26,0,498.066667,4,1440,388.490234,0,0,30,100,100,True
9,6_11_and_15_20,False,9,28,0,495.333333,2,1440,395.452259,0,0,30,100,100,True

In [4]:
# Generate CSV file
batch_run_results.to_csv('data.csv', index=False)

In [20]:
# from scipy.stats import f_oneway
raw_option_1 = batch_run_results.loc[batch_run_results["policy_range_time"] == "7_10_and_16_19"]
mean_option_1 = raw_option_1["MeanTravelTime"]

raw_option_2 = batch_run_results.loc[batch_run_results["policy_range_time"] == "8_11_and_17_20"]
mean_option_2 = raw_option_2["MeanTravelTime"]

raw_option_3 = batch_run_results.loc[batch_run_results["policy_range_time"] == "8_11_and_17_20"]
mean_option_3 = raw_option_3["MeanTravelTime"]

raw_option_4 = batch_run_results.loc[batch_run_results["policy_range_time"] == "8_11_and_17_20"]
mean_option_4 = raw_option_4["MeanTravelTime"]

raw_option_5 = batch_run_results.loc[batch_run_results["policy_range_time"] == "8_11_and_17_20"]
mean_option_5 = raw_option_5["MeanTravelTime"]

f_oneway(mean_option_1, mean_option_2, mean_option_3, mean_option_4, mean_option_5)

SyntaxError: invalid syntax (<ipython-input-20-06a1a32b16e0>, line 2)