In [1]:
# Library Import
from mesa.batchrunner import BatchRunner
from road_network_model.model import RoadNetworkModel, number_idle_cars, number_move_cars, number_finished_cars, simulation_minutes, number_office, number_residence, mean_travel_time, std_travel_time

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Mesa BatchRunner
fixed_params = {"number_of_cars": 30,
                "width": 100,
                "height": 100,
                "is_odd_even_policy_enabled": True
               }

variable_params = {"policy_range_time": [
                        '7_10_and_16_19',
                        '8_11_and_17_20',
                        '6_9_and_15_18',
                        '8_9_and_17_18',
                        '6_11_and_15_20'
                    ],
                    "is_odd_date": [True, False]
                  }
batch_run = BatchRunner(RoadNetworkModel,
                        variable_parameters=variable_params,
                        fixed_parameters=fixed_params,
                        iterations=5,
                        max_steps=1500,
                        model_reporters={
                            "Idle": number_idle_cars,
                            "Move": number_move_cars,
                            "Finished": number_finished_cars,
                            "SimulationMinutes": simulation_minutes,
                            "ToOffice": number_office,
                            "ToResidence": number_residence,
                            "MeanTravelTime": mean_travel_time,
                            "StdTravelTime": std_travel_time
                        }
                       )

batch_run.run_all()

batch_run_results = batch_run.get_model_vars_dataframe()
batch_run_results.head()

50it [2:20:33, 168.66s/it]

,is_odd_date,policy_range_time,Run,Finished,Idle,MeanTravelTime,Move,SimulationMinutes,StdTravelTime,ToOffice,ToResidence,number_of_cars,width,height,is_odd_even_policy_enabled
0,7_10_and_16_19,True,0,27,0,489.133333,3,1440,392.442160,0,0,30,100,100,True
1,7_10_and_16_19,True,1,27,0,510.400000,3,1440,381.376245,0,0,30,100,100,True
2,7_10_and_16_19,True,2,27,0,477.400000,3,1440,396.196971,0,0,30,100,100,True
3,7_10_and_16_19,True,3,27,0,485.200000,3,1440,385.197646,0,0,30,100,100,True
4,7_10_and_16_19,True,4,27,0,483.866667,3,1440,382.710311,0,0,30,100,100,True

In [3]:
batch_run_results

,is_odd_date,policy_range_time,Run,Finished,Idle,MeanTravelTime,Move,SimulationMinutes,StdTravelTime,ToOffice,ToResidence,number_of_cars,width,height,is_odd_even_policy_enabled
0,7_10_and_16_19,True,0,27,0,489.133333,3,1440,392.442160,0,0,30,100,100,True
1,7_10_and_16_19,True,1,27,0,510.400000,3,1440,381.376245,0,0,30,100,100,True
2,7_10_and_16_19,True,2,27,0,477.400000,3,1440,396.196971,0,0,30,100,100,True
3,7_10_and_16_19,True,3,27,0,485.200000,3,1440,385.197646,0,0,30,100,100,True
4,7_10_and_16_19,True,4,27,0,483.866667,3,1440,382.710311,0,0,30,100,100,True
5,7_10_and_16_19,False,5,27,0,500.466667,3,1440,383.051148,0,0,30,100,100,True
6,7_10_and_16_19,False,6,27,0,498.066667,3,1440,385.457125,0,0,30,100,100,True
7,7_10_and_16_19,False,7,28,0,482.600000,2,1440,388.399159,0,0,30,100,100,True
8,7_10_and_16_19,False,8,27,0,492.200000,3,1440,385.144942,0,0,30,100,100,True
9,7_10_and_16_19,False,9,28,0,493.133333,2,1440,382.580600,0,0,30,100,100,True
10,8_11_and_17_20,True,10,27,0,484.266667,3,1440,394.827467,0,0,30,100,100,True
11,8_11_and_17_20,True,11,27,0,487.600000,3,1440,384.091447,0,0,30,100,100,True
12,8_11_and_17_20,True,12,27,0,503.266667,3,1440,391.398001,0,0,30,100,100,True
13,8_11_and_17_20,True,13,27,0,482.866667,3,1440,409.480544,0,0,30,100,100,True
14,8_11_and_17_20,True,14,27,0,492.400000,3,1440,403.010471,0,0,30,100,100,True
15,8_11_and_17_20,False,15,28,0,499.600000,2,1440,400.532779,0,0,30,100,100,True
16,8_11_and_17_20,False,16,27,0,512.066667,3,1440,383.862296,0,0,30,100,100,True
17,8_11_and_17_20,False,17,27,0,509.400000,3,1440,409.611247,0,0,30,100,100,True
18,8_11_and_17_20,False,18,27,0,532.000000,3,1440,376.045742,0,0,30,100,100,True
19,8_11_and_17_20,False,19,27,0,517.866667,3,1440,388.838247,0,0,30,100,100,True
20,6_9_and_15_18,True,20,27,0,474.800000,3,1440,394.084458,0,0,30,100,100,True
21,6_9_and_15_18,True,21,27,0,481.333333,3,1440,388.030354,0,0,30,100,100,True
22,6_9_and_15_18,True,22,28,0,504.633333,2,1440,383.301490,0,0,30,100,100,True
23,6_9_and_15_18,True,23,27,0,497.666667,3,1440,401.341113,0,0,30,100,100,True
24,6_9_and_15_18,True,24,27,0,504.733333,3,1440,394.906397,0,0,30,100,100,True
25,6_9_and_15_18,False,25,27,0,487.733333,3,1440,391.359250,0,0,30,100,100,True
26,6_9_and_15_18,False,26,27,0,497.866667,3,1440,394.176926,0,0,30,100,100,True
27,6_9_and_15_18,False,27,27,0,494.233333,3,1440,394.139712,0,0,30,100,100,True
28,6_9_and_15_18,False,28,27,0,475.266667,3,1440,395.911601,0,0,30,100,100,True
29,6_9_and_15_18,False,29,27,0,484.066667,3,1440,401.360846,0,0,30,100,100,True
30,8_9_and_17_18,True,30,27,0,478.933333,3,1440,401.548580,0,0,30,100,100,True
31,8_9_and_17_18,True,31,28,0,488.333333,2,1440,389.693583,0,0,30,100,100,True
32,8_9_and_17_18,True,32,27,0,476.733333,3,1440,394.383395,0,0,30,100,100,True
33,8_9_and_17_18,True,33,28,0,489.266667,2,1440,398.363815,0,0,30,100,100,True
34,8_9_and_17_18,True,34,28,0,473.566667,2,1440,397.296504,0,0,30,100,100,True
35,8_9_and_17_18,False,35,27,0,486.666667,3,1440,383.803538,0,0,30,100,100,True
36,8_9_and_17_18,False,36,27,0,477.333333,3,1440,395.841158,0,0,30,100,100,True
37,8_9_and_17_18,False,37,27,0,483.866667,3,1440,397.715119,0,0,30,100,100,True
38,8_9_and_17_18,False,38,27,0,481.866667,3,1440,380.566221,0,0,30,100,100,True
39,8_9_and_17_18,False,39,27,0,481.800000,3,1440,382.745642,0,0,30,100,100,True
40,6_11_and_15_20,True,40,28,0,510.200000,2,1440,390.941547,0,0,30,100,100,True
41,6_11_and_15_20,True,41,27,0,490.133333,3,1440,392.281509,0,0,30,100,100,True
42,6_11_and_15_20,True,42,27,0,494.266667,3,1440,389.821406,0,0,30,100,100,True
43,6_11_and_15_20,True,43,27,0,497.466667,3,1440,389.287532,0,0,30,100,100,True
44,6_11_and_15_20,True,44,27,0,518.400000,3,1440,386.393720,0,0,30,100,100,True
45,6_11_and_15_20,False,45,28,0,511.233333,2,1440,371.726753,0,0,30,100,100,True
46,6_11_and_15_20,False,46,28,0,517.400000,2,1440,399.907706,0,0,30,100,100,True
47,6_11_and_15_20,False,47,25,0,488.400000,5,1440,417.156853,0,0,30,100,100,True
48,6_11_and_15_20,False,48,26,0,496.133333,4,1440,401.355016,0,0,30,100,100,True
49,6_11_and_15_20,False,49,27,0,485.133333,3,1440,377.233679,0,0,30,100,100,True

In [4]:
# Generate CSV file
batch_run_results.to_csv('data.csv', index=False)

In [9]:
from scipy.stats import f_oneway
raw_option_1 = batch_run_results.loc[batch_run_results["is_odd_date"] == "7_10_and_16_19"]
mean_option_1 = raw_option_1["MeanTravelTime"]

raw_option_2 = batch_run_results.loc[batch_run_results["is_odd_date"] == "8_11_and_17_20"]
mean_option_2 = raw_option_2["MeanTravelTime"]

raw_option_3 = batch_run_results.loc[batch_run_results["is_odd_date"] == "6_9_and_15_18"]
mean_option_3 = raw_option_3["MeanTravelTime"]

raw_option_4 = batch_run_results.loc[batch_run_results["is_odd_date"] == "8_9_and_17_18"]
mean_option_4 = raw_option_4["MeanTravelTime"]

raw_option_5 = batch_run_results.loc[batch_run_results["is_odd_date"] == "6_11_and_15_20"]
mean_option_5 = raw_option_5["MeanTravelTime"]

print(mean_option_1)

f_oneway(mean_option_1, mean_option_2, mean_option_3, mean_option_4, mean_option_5)

0    489.133333
1    510.400000
2    477.400000
3    485.200000
4    483.866667
5    500.466667
6    498.066667
7    482.600000
8    492.200000
9    493.133333
Name: MeanTravelTime, dtype: float64

F_onewayResult(statistic=5.337019919184443, pvalue=0.0013244886543413669)

In [ ]:
# Mesa BatchRunner
fixed_params = {"number_of_cars": 30,
                "width": 100,
                "height": 100,
                "is_odd_even_policy_enabled": False
               }

variable_params = {"policy_range_time": ['7_10_and_16_19'],
                    "is_odd_date": [True]
                  }
batch_run_2 = BatchRunner(RoadNetworkModel,
                        variable_parameters=variable_params,
                        fixed_parameters=fixed_params,
                        iterations=1,
                        max_steps=1500,
                        model_reporters={
                            "Idle": number_idle_cars,
                            "Move": number_move_cars,
                            "Finished": number_finished_cars,
                            "SimulationMinutes": simulation_minutes,
                            "ToOffice": number_office,
                            "ToResidence": number_residence,
                            "MeanTravelTime": mean_travel_time,
                            "StdTravelTime": std_travel_time
                        }
                       )

batch_run_2.run_all()

batch_run_results_2 = batch_run_2.get_model_vars_dataframe()
batch_run_results_2.head()